# Uncomment this line to define a global platform for your project 
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

target 'Healthcover' do 
pod 'Google/SignIn'
pod 'SDWebImage', '~>3.7' 
end 

target 'HealthcoverTests' do 

end